### ISSUE TITLE
使用文件储存

### ISSUE THREAD

**Issue by oovm** [lcolok/OneClick-stable-diffusion#1]
芜湖区没有网盘, 咨询客服,, 客服说用文件储存, 并且说以后网盘都会转为文件储存.

文件存储在实例中的挂载目录为：`/root/autodl-fs`, 大小同样是 20G.

**Comment by lcolok** [comment]
使用/root/autodl-fs可能会另外增加费用，超出20G的部分应该是需要另外扣费的，持续观望一下

**Comment by lcolok** [comment]
> 芜湖区没有网盘, 咨询客服,, 客服说用文件储存, 并且说以后网盘都会转为文件储存.
> 
> 文件存储在实例中的挂载目录为：`/root/autodl-fs`, 大小同样是 20G.

使用/root/autodl-fs可能会另外增加费用，超出20G的部分应该是需要另外扣费的，持续观望一下

**Comment by lcolok** [comment]
> 芜湖区没有网盘, 咨询客服,, 客服说用文件储存, 并且说以后网盘都会转为文件储存.
> 
> 文件存储在实例中的挂载目录为：`/root/autodl-fs`, 大小同样是 20G.

你可以通过手动修改stable-diffusion-webui目录下的config.json中的"outdir_txt2img_samples"、"outdir_img2img_samples"、"outdir_extras_samples"、"outdir_txt2img_grids"、"outdir_img2img_grids"这几个参数指定的路径来实现你的需求
