### ISSUE TITLE
下载脚本

### ISSUE THREAD

**Issue by oovm** [lcolok/OneClick-stable-diffusion#2]
最好加一个下载脚本到 outputs 文件夹, 打包以后可以关掉服务器进网盘慢慢下

不然下载的时候也要计费, 而且特别容易中断.

脚本大致如下:

```shell
# download.ipynb
!rm -f 'download.tar.gz'
!tar -czvf 'download.tar.gz' txt2img-images txt2img-grids img2img-images img2img-grids 
!rm -rf txt2img-images
!rm -rf txt2img-grids
!rm -rf img2img-images
!rm -rf img2img-grids
```

**Comment by lcolok** [comment]
> 最好加一个下载脚本到 outputs 文件夹, 打包以后可以关掉服务器进网盘慢慢下
> 
> 不然下载的时候也要计费, 而且特别容易中断.
> 
> 脚本大致如下:
> 
> ```shell
> # download.ipynb
> !rm -f 'download.tar.gz'
> !tar -czvf 'download.tar.gz' txt2img-images txt2img-grids img2img-images img2img-grids 
> !rm -rf txt2img-images
> !rm -rf txt2img-grids
> !rm -rf img2img-images
> !rm -rf img2img-grids
> ```

已经追加了相关脚本packNasOutputsAndClean.ipynb，在tools/pack_tools目录下
